apiVersion: v1
kind: Service
metadata:
  name: mongo-product-svc
  namespace: dev
  labels:
    name: mongo-product-svc
spec:
  clusterIP: None
  selector:
    role: product-db
  ports:
    - port: 27018
      targetPort: 27017